# Generated by Django 5.1.4 on 2025-01-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilityapp', '0002_alter_awards_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'mm_language',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_of_birth', models.DateField()),
                ('about', models.TextField()),
                ('occupations', models.TextField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilityapp.address')),
            ],
            options={
                'db_table': 'crew',
            },
        ),
        migrations.CreateModel(
            name='ProductionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('founded_year', models.PositiveIntegerField()),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('domains', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logos/')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utilityapp.address')),
            ],
            options={
                'db_table': 'productionhouse',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('released_date', models.DateField()),
                ('description', models.TextField()),
                ('song_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_managment.language')),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
