# Generated by Django 5.1.4 on 2025-01-02 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0001_initial'),
        ('utilityapp', '0002_alter_awards_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_office_collections', models.DecimalField(decimal_places=2, max_digits=15)),
                ('advertisement', models.DecimalField(decimal_places=2, max_digits=15)),
                ('domestic_collection', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=15)),
                ('first_date', models.DecimalField(decimal_places=2, max_digits=15)),
                ('first_week', models.DecimalField(decimal_places=2, max_digits=15)),
                ('first_month', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilityapp.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_managment.language')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_managment.movie')),
                ('movie_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_review',
            },
        ),
        migrations.CreateModel(
            name='MusicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField()),
                ('music_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_managment.song')),
            ],
            options={
                'db_table': 'music_review',
            },
        ),
    ]
