# Generated by Django 5.1.4 on 2025-01-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0002_collection_movie_moviereview_musicreview'),
        ('utilityapp', '0002_alter_awards_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_house_name', models.CharField(max_length=200)),
                ('contacts', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilityapp.address')),
            ],
            options={
                'db_table': 'distribution_house',
            },
        ),
    ]
