# Generated by Django 5.1.4 on 2025-01-03 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0005_awardsong_movieaward_delete_awardcrew'),
        ('utilityapp', '0002_alter_awards_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('award_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilityapp.awards')),
                ('crew_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_managment.crew')),
            ],
            options={
                'db_table': 'awardcrew',
            },
        ),
    ]
