# Generated by Django 5.1.4 on 2025-01-09 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0006_awardcrew'),
        ('utilityapp', '0004_alter_awards_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew', to='utilityapp.address'),
        ),
        migrations.AlterField(
            model_name='distributionhouse',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_house', to='utilityapp.address'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='utilityapp.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_language', to='movie_managment.language'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviereview', to='movie_managment.movie'),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='movie_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviereview_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicreview',
            name='music_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_musicreview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicreview',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicreview', to='movie_managment.song'),
        ),
        migrations.AlterField(
            model_name='productionhouse',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_house', to='utilityapp.address'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song', to='movie_managment.language'),
        ),
    ]
