# Generated by Django 5.1.4 on 2025-01-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0007_alter_crew_address_alter_distributionhouse_address_and_more'),
        ('utilityapp', '0004_alter_awards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardcrew',
            name='award_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awardcrew', to='utilityapp.awards'),
        ),
        migrations.AlterField(
            model_name='awardcrew',
            name='crew_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crewaward', to='movie_managment.crew'),
        ),
        migrations.AlterField(
            model_name='awardsong',
            name='award_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_song', to='utilityapp.awards'),
        ),
        migrations.AlterField(
            model_name='awardsong',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_award', to='movie_managment.song'),
        ),
        migrations.AlterField(
            model_name='movieaward',
            name='award_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_movie', to='utilityapp.awards'),
        ),
        migrations.AlterField(
            model_name='movieaward',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_award', to='movie_managment.movie'),
        ),
        migrations.AlterField(
            model_name='moviecollection',
            name='collection_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectioncategory', to='utilityapp.category'),
        ),
        migrations.AlterField(
            model_name='moviecollection',
            name='collection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_movie', to='movie_managment.collection'),
        ),
        migrations.AlterField(
            model_name='moviecollection',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_collection', to='movie_managment.movie'),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='crew_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crewcategory', to='utilityapp.category'),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='crew_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_movie', to='movie_managment.crew'),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_crew', to='movie_managment.movie'),
        ),
        migrations.AlterField(
            model_name='moviemusic',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_music', to='movie_managment.movie'),
        ),
        migrations.AlterField(
            model_name='moviemusic',
            name='music_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musiccategory', to='utilityapp.category'),
        ),
        migrations.AlterField(
            model_name='moviemusic',
            name='song_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_movie', to='movie_managment.song'),
        ),
    ]
