# Generated by Django 5.1.4 on 2025-01-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_managment', '0008_alter_awardcrew_award_id_alter_awardcrew_crew_id_and_more'),
        ('utilityapp', '0004_alter_awards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'movie'}, on_delete=django.db.models.deletion.CASCADE, related_name='movie_category', to='utilityapp.category'),
        ),
    ]
