# Generated by Django 5.1.4 on 2025-01-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_profileuser_table'),
        ('utilityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilityapp.address'),
        ),
    ]
