# Generated by Django 5.1.4 on 2025-01-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilityapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilityapp.category'),
        ),
    ]
